# Default lease duration (in seconds) for dynamically assigned IP addresses
default-lease-time 3600;

# DHCP configuration for the private subnet connected to r9
subnet 192.168.1.0 netmask 255.255.255.0 {

    # Range of IP addresses that can be dynamically assigned to DHCP clients
    # .1 is excluded because it is statically assigned to r9
    range 192.168.1.2 192.168.1.254;

    # Default gateway provided to DHCP clients (r9)
    option routers 192.168.1.1;
}


