#See CollisionDomainsExplanation.TXT 

pc1[0]=A
r1[0]=A

r1[1]=B
r2[0]=B

r1[2]=C
r4[1]=C

r1[3]=D
r3[0]=D

r2[1]=E
r4[0]=E

r3[1]=F
r4[2]=F

r4[3]=G
r5[0]=G

r5[1]=H
r8[0]=H

r5[2]=I
r7[1]=I

r5[3]=J
r6[0]=J

r8[1]=K
r6[1]=K

r8[2]=L
r7[0]=L

r8[3]=M
r9[1]=M

r9[0]=N
pc2[0]=N
s2[0]=N

r6[2]=O
r7[2]=O

r6[3]=P
s1[0]=P

r7[3]=Q
r10[0]=Q

#I don’t know why I decided to change the interface logic right at the last moment.
#It was too late to change it when I realized it.
r10[1]=R
pc3[0]=R
s3[0]=R